wifi:
  vlan_id: 851
  switches:
    - "B09-B"
    - "B12-B"
    - "B15-B"
    - "C01-A"
    - "C08-A"
    - "C14-A"
    - "D06-B"
    - "LN02-A"
    - "LN06-A"

models:
  - name: "WS-C2960G-48TC-L"
    path: "/scripts/swboot/switchconfig/c2960g.cfg"
    ports: 48
  - name: "WS-C2960X-48TS-L"
    path: "/scripts/swboot/switchconfig/c2960x.cfg"
    ports: 48
  - name: "WS-C2960X-48LPD-L"
    path: "/scripts/swboot/switchconfig/c2960x.cfg"
    ports: 48
  - name: "WS-C2960-24TC-L"
    path: "/scripts/swboot/switchconfig/c2960.cfg"
    ports: 24
  - name: "WS-C2960-24PC-S"
    path: "/scripts/swboot/switchconfig/c2960.cfg"
    ports: 24
  - name: "WS-C2960-24LT-L"
    path: "/scripts/swboot/switchconfig/c2960.cfg"
    ports: 24
  - name: "WS-C2960-8TC-L"
    path: "/scripts/swboot/switchconfig/c2960.cfg"
    ports: 8
  - name: "WS-C2960-8TC-S"
    path: "/scripts/swboot/switchconfig/c2960.cfg"
    ports: 8
  - name: "WS-C3560-8PC-S"
    path: "/scripts/swboot/switchconfig/c3560.cfg"
    ports: 8
  - name: "WS-C3560-24PC-S"
    path: "/scripts/swboot/switchconfig/c3560.cfg"
    ports: 24
  - name: "WS-C3560G-24TS-S"
    path: "/scripts/swboot/switchconfig/c3560g.cfg"
    ports: 24
  - name: "WS-C2960S-24PS-L"
    path: "/scripts/swboot/switchconfig/c2960s.cfg"
    ports: 24
  - name: "WS-C2960S-48PS-L"
    path: "/scripts/swboot/switchconfig/c2960s.cfg"
    ports: 48
  - name: "WS-C3560G-48TS-S"
    path: "/scripts/swboot/switchconfig/c3560g.cfg"
    ports: 48
  - name: "WS-C3750-48TS-S"
    path: "/scripts/swboot/switchconfig/c3750.cfg"
    ports: 24
  - name: "WS-C3750G-24PS-S"
    path: "/scripts/swboot/switchconfig/c3750g.cfg"
    ports: 24
  - name: "WS-C3750G-48PS-S"
    path: "/scripts/swboot/switchconfig/c3750g.cfg"
    ports: 48

static_files:
  - c2950.bin: "/scripts/swboot/switchconfig/ios/c2950-i6k2l2q4-mz.121-22.EA14.bin"
  - c2960-lanbase.tar: "/scripts/swboot/switchconfig/ios/c2960-lanbasek9-tar.150-2.SE11.tar"
  - c2960-lanlite.tar: "/scripts/swboot/switchconfig/ios/c2960-lanlitek9-tar.150-2.SE11.tar"
  - c3560-ip.tar: "/scripts/swboot/switchconfig/ios/c3560-ipservicesk9-tar.150-2.SE11.tar"
  - c3750-ip.tar: "/scripts/swboot/switchconfig/ios/c3750-ipservicesk9-tar.150-2.SE11.tar"
  - c4500e.bin: "/scripts/swboot/switchconfig/ios/cat4500e-entservicesk9-mz.152-2.E8.bin"

